version: '3'
services:

  redis:
    image: 'redis:5.0-alpine'
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: python /app/code/ecommerce_tasks.py
