version: '3'
services:
  db:
    build: 
      context: .
    environment:
      POSTGRES_DB: myDBname
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: hey_NSA
    ports:
      - 5432:5432
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./:/usr/src/app
