version: '3.3'
services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
    ports:
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - my_net

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    command:
      # - --web.console.templates=/etc/prometheus/consoles
      # - --web.console.libraries=/etc/prometheus/console_libraries
      # - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      # - --storage.tsdb.path=/prometheus
      # - --web.enable-lifecycle
      # - --web.route-prefix=/
    volumes:
      - ./confs/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    networks:
      - my_net

  # OpenTelemetry Collector
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./confs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./confs/server.crt:/etc/tls/server.crt
      - ./confs/server.key:/etc/tls/server.key
      - ./confs/rootCA.crt:/etc/tls/rootCA.crt
    ports:
      - "4317:4317" # OTLP over gRPC receiver
      - "9464:9464" # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
    networks:
      - my_net

networks:
  my_net: null
